name: disjoint-polymorphism
version: 0.1.0.0
synopsis: A prototype-based, statically typed language
description: Please see README.md
category: Language
author: Anonymous
maintainer: anonymous@gmail.com
copyright: 2016-2017, Anonymous
license: BSD3
github: anonymous/disjoint-polymorphism
dependencies:
  - ansi-wl-pprint
  - base >=4.7 && <5
  - mtl
  - repline
  - array
  - containers
  - protolude
  - text
  - filepath
  - directory

ghc-options:
  - -fwarn-tabs
  - -fwarn-unused-imports
  - -fwarn-missing-signatures
  - -fwarn-name-shadowing
  - -fwarn-incomplete-patterns

library:
  source-dirs: src
  build-tools:
  - alex
  - happy
  exposed-modules:
    - Lexer
    - Environment
    - Common
    - PrettyPrint
    - Utility
    - Source.Parser
    - Source.Syntax
    - Source.Subtyping
    - Source.Typing
    - Source.Desugar
    - Source.SrcLoc
    - Target.Syntax
    - Target.Dynamics
    - Target.CBN
  dependencies:
    - unbound

executables:
  disjoint-polymorphism-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - disjoint-polymorphism

tests:
  disjoint-polymorphism-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tasty >=0.11.1
      - tasty-hspec >=1.1.3.1
      - disjoint-polymorphism
